# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fc0a4ced8b667a7c38b23105019fb57e5a12e4af99278b7b2dcd03c34c368f12607460be2792b1bbd91c55bd20ff194c58a851517b73960c6ec85b138162c3d

test:
  secret_key_base: c6cf40d1ef637607ae00797fade5299880488780e4fcc83a1d1444686af49b6e2b942af06aa3488e97b76bba6e17db4c2c5c2dfda468d5090ac99009eab8455f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
